import { GitProvider } from '../providers';
import { ReviewIssue, ReviewComment, ReviewSummary } from '../types';
import { logger } from '../logging';
import { Config } from '../config/schema';

export class CommentPublisher {
  private provider: GitProvider;
  private config: Config;

  constructor(provider: GitProvider, config: Config) {
    this.provider = provider;
    this.config = config;
  }

  /**
   * Post inline comments for review issues
   */
  async postInlineComments(
    repo: string,
    prNumber: number,
    issues: ReviewIssue[]
  ): Promise<Map<string, string>> {
    const commentIds = new Map<string, string>();

    for (const issue of issues) {
      try {
        const comment = this.formatInlineComment(issue);
        const result = await this.provider.postInlineComment(repo, prNumber, comment);
        commentIds.set(this.getIssueKey(issue), result.id);
        
        logger.debug({ issue: issue.title, commentId: result.id }, 'Posted inline comment');
      } catch (error: any) {
        logger.error(
          { error: error.message, issue: issue.title, file: issue.file, line: issue.start_line },
          'Failed to post inline comment'
        );
        // Continue with other comments
      }
    }

    logger.info({ totalComments: commentIds.size, totalIssues: issues.length }, 'Inline comments posted');
    return commentIds;
  }

  /**
   * Post a summary comment with all findings
   */
  async postSummary(
    repo: string,
    prNumber: number,
    issues: ReviewIssue[],
    commentIds: Map<string, string>
  ): Promise<void> {
    if (!this.config.review.summary_enabled) {
      logger.info('Summary disabled in config');
      return;
    }

    const summary = this.buildSummary(issues);
    const body = this.formatSummaryComment(summary, issues, commentIds);

    await this.provider.postReviewSummary(repo, prNumber, summary, body);
    logger.info('Posted review summary');
  }

  /**
   * Add labels based on findings
   */
  async addLabels(repo: string, prNumber: number, issues: ReviewIssue[]): Promise<void> {
    if (!this.config.review.labeling_enabled) {
      logger.info('Labeling disabled in config');
      return;
    }

    const labels = this.determineLabels(issues);
    
    if (labels.length > 0) {
      await this.provider.addLabels(repo, prNumber, labels);
      logger.info({ labels }, 'Added labels to PR');
    }
  }

  private formatInlineComment(issue: ReviewIssue): ReviewComment {
    const severityEmoji = {
      critical: '🚨',
      high: '⚠️',
      medium: '⚡',
      low: '💡',
    };

    const categoryEmoji = {
      security: '🔒',
      reliability: '🛡️',
      performance: '⚡',
      maintainability: '🔧',
      style: '✨',
    };

    const tags = `[${severityEmoji[issue.severity]} ${issue.severity.toUpperCase()}] [${categoryEmoji[issue.category]} ${issue.category}] [Confidence: ${(issue.confidence * 100).toFixed(0)}%]`;

    let body = `### ${issue.title}\n\n`;
    body += `${tags}\n\n`;
    body += `**Why it matters:**\n${issue.explanation}\n\n`;
    body += `**Suggested fix:**\n\`\`\`suggestion\n${issue.suggested_fix}\n\`\`\`\n\n`;
    
    if (issue.references && issue.references.length > 0) {
      body += `**References:**\n${issue.references.map(ref => `- ${ref}`).join('\n')}\n\n`;
    }

    body += `<details>\n<summary>Rationale</summary>\n\n${issue.rationale}\n</details>\n\n`;
    body += `---\n*🤖 Generated by pr-ai-reviewer*`;

    return {
      path: issue.file,
      line: issue.start_line,
      side: 'RIGHT',
      body,
      issue,
    };
  }

  private buildSummary(issues: ReviewIssue[]): ReviewSummary {
    const summary: ReviewSummary = {
      total_issues: issues.length,
      by_severity: {},
      by_category: {},
      risk_score: 0,
      recommendations: [],
      inline_comment_refs: [],
    };

    // Count by severity and category
    for (const issue of issues) {
      summary.by_severity[issue.severity] = (summary.by_severity[issue.severity] || 0) + 1;
      summary.by_category[issue.category] = (summary.by_category[issue.category] || 0) + 1;
    }

    // Calculate risk score (0-100)
    const weights = { critical: 10, high: 5, medium: 2, low: 1 };
    let totalWeight = 0;
    for (const [severity, count] of Object.entries(summary.by_severity)) {
      totalWeight += (weights[severity as keyof typeof weights] || 0) * count;
    }
    summary.risk_score = Math.min(100, totalWeight);

    // Generate recommendations
    if (summary.by_severity.critical > 0) {
      summary.recommendations.push('⚠️ Critical issues found - address immediately before merging');
    }
    if (summary.by_severity.high > 0) {
      summary.recommendations.push('Review and resolve high-severity issues');
    }
    if (summary.by_category.security > 0) {
      summary.recommendations.push('🔒 Security concerns detected - ensure thorough review');
    }
    if (summary.risk_score > 50) {
      summary.recommendations.push('Consider breaking this PR into smaller, more focused changes');
    }

    return summary;
  }

  private formatSummaryComment(
    summary: ReviewSummary,
    issues: ReviewIssue[],
    commentIds: Map<string, string>
  ): string {
    let body = '## 🤖 AI Code Review Summary\n\n';

    // Risk score
    const riskColor = summary.risk_score > 70 ? '🔴' : summary.risk_score > 40 ? '🟡' : '🟢';
    body += `**Risk Score:** ${riskColor} ${summary.risk_score}/100\n\n`;

    // Overall stats
    body += `**Total Issues Found:** ${summary.total_issues}\n\n`;

    // Breakdown by severity
    if (Object.keys(summary.by_severity).length > 0) {
      body += '### Issues by Severity\n\n';
      const severityOrder = ['critical', 'high', 'medium', 'low'];
      for (const severity of severityOrder) {
        const count = summary.by_severity[severity];
        if (count) {
          const emoji = { critical: '🚨', high: '⚠️', medium: '⚡', low: '💡' }[severity];
          body += `- ${emoji} **${severity.toUpperCase()}:** ${count}\n`;
        }
      }
      body += '\n';
    }

    // Breakdown by category
    if (Object.keys(summary.by_category).length > 0) {
      body += '### Issues by Category\n\n';
      for (const [category, count] of Object.entries(summary.by_category)) {
        const emoji = {
          security: '🔒',
          reliability: '🛡️',
          performance: '⚡',
          maintainability: '🔧',
          style: '✨',
        }[category] || '📋';
        body += `- ${emoji} **${category}:** ${count}\n`;
      }
      body += '\n';
    }

    // Recommendations
    if (summary.recommendations.length > 0) {
      body += '### Recommendations\n\n';
      for (const rec of summary.recommendations) {
        body += `- ${rec}\n`;
      }
      body += '\n';
    }

    // Top issues summary
    const criticalAndHigh = issues.filter(i => i.severity === 'critical' || i.severity === 'high');
    if (criticalAndHigh.length > 0) {
      body += '### Top Issues\n\n';
      for (const issue of criticalAndHigh.slice(0, 5)) {
        const emoji = issue.severity === 'critical' ? '🚨' : '⚠️';
        body += `${emoji} **[${issue.file}:${issue.start_line}]** ${issue.title}\n`;
      }
      body += '\n';
    }

    body += '---\n';
    body += '*Review detailed inline comments above for specific recommendations and fixes.*\n\n';
    body += `*Generated by pr-ai-reviewer • Model: ${this.config.ollama.model}*`;

    return body;
  }

  private determineLabels(issues: ReviewIssue[]): string[] {
    const labels: Set<string> = new Set(['ai-review']);

    // Add severity labels
    if (issues.some(i => i.severity === 'critical')) {
      labels.add('needs-attention');
    }

    // Add category labels
    const categories = new Set(issues.map(i => i.category));
    if (categories.has('security')) labels.add('security');
    if (categories.has('performance')) labels.add('performance');
    if (categories.has('reliability')) labels.add('bug');

    return Array.from(labels);
  }

  private getIssueKey(issue: ReviewIssue): string {
    return `${issue.file}:${issue.start_line}:${issue.title}`;
  }
}
